### ISSUE TITLE
No negative weights for moon cycle OR cap min-score at 0%

### ISSUE THREAD

**Issue by bustinjurkz** [CyberTropic/StellarGaze#69]
![image](https://user-images.githubusercontent.com/28364145/64511766-f8b2f480-d2b2-11e9-8424-f39b94f5595f.png)

We could easily just go if score <0, return 0, depends how much we want the moon to punish.  easy fix, just confirm what you wanna do

**Comment by CyberTropic** [comment]
I'd say moon to 0 imo
